name: Publish Image

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

permissions:
  id-token: write # JWT tokens for S3 OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::178851224597:role/GitHubActionFullAccessDevContainerCacheS3
          aws-region: us-east-1
          role-duration-seconds: 21600
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: breezewish/tiflash-dev
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=s3,bucket=wenxuan-tiflash-devcontainer-cache,region=us-east-1,name=gha-${{ github.ref_name }}
            type=s3,bucket=wenxuan-tiflash-devcontainer-cache,region=us-east-1,name=gha-main
          cache-to: type=s3,bucket=wenxuan-tiflash-devcontainer-cache,region=us-east-1,name=gha-${{ github.ref_name }},mode=max
